name: bloc_ecommerce
description: "A ecommerce app using bloc state management & firebase backend"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_facebook_auth: ^6.1.1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  gap: ^3.0.1
  go_router: ^13.2.0
  google_sign_in: ^6.2.1
  loading_animation_widget: ^1.2.0+4
  lottie: ^3.1.0
  meta: ^1.11.0
  readmore: ^2.2.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  social_login_buttons: ^1.0.7
  twitter_login: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/anim/
